In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../data/raw/raw_Data.csv")

In [6]:
df.sample(10)

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes
592,3,132,80,0,0,34.4,0.402,44,1
541,3,128,72,25,190,32.4,0.549,27,1
764,2,122,70,27,0,36.8,0.340,27,0
190,3,111,62,0,0,22.6,0.142,21,0
200,0,113,80,16,0,31.0,0.874,21,0
253,0,86,68,32,0,35.8,0.238,25,0
486,1,139,62,41,480,40.7,0.536,21,0
581,6,109,60,27,0,25.0,0.206,27,0
111,8,155,62,26,495,34.0,0.543,46,1
419,3,129,64,29,115,26.4,0.219,28,1

In [7]:
df.describe()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
x = df.drop(columns='diabetes',axis=1)
y = df['diabetes']
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [9]:
x_train.shape , y_train.shape

((614, 8), (614,))

In [10]:
standardtransformer = ColumnTransformer([
    ('standardscaler',StandardScaler(),slice(0,8))
],remainder='passthrough')

In [11]:
from sklearn.linear_model import LogisticRegression
pipe = Pipeline(steps=[
    ('standardscalerpipeline',standardtransformer)
])

In [12]:
transformed_Data =pipe.fit_transform(x)

In [13]:
transformed_Data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [14]:
x.columns

Index(['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin',
       'bmi', 'diab_pred', 'age'],
      dtype='object')

In [15]:
columns = ['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin',
       'bmi', 'diab_pred', 'age']

In [16]:
transformed_df = pd.DataFrame(transformed_Data, columns=x.columns)

In [17]:
transformed_df

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [18]:
transformed_df['Outcome'] = y.values

In [19]:
transformed_df

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,Outcome
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995,1
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672,0
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584,1
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549,0
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496,1
...,...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136,0
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023,0
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760,0
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732,1
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374,0

In [20]:
transformed_df.to_csv('../data/raw/raw_Data.csv', index=False,mode='w')